### ISSUE TITLE
Install.bat not working right 

### ISSUE THREAD

**Issue by jdunkerley** [jdunkerley/AlteryxAddIns#11]
Ravi and Rob can't get intall.bat to put ini file in correct place,.

**Comment by jdunkerley** [comment]
Current version seems to produce ini file correctly but not being loaded on Rob's machine

**Comment by mjakefranklin** [comment]
Was there a solution to this issue?  Currently, after running Install.bat, the new "JDTools" category will not show up in Alteryx Designer (10.6.8.17850).  I have verified that the ini file was placed in the proper location:

C:\Program Files\Alteryx\Settings\AdditionalPlugins\JDTools.ini

It contains:

[Settings]
x64Path=C:\OmniBus\ALTERY~2
x86Path=C:\OmniBus\ALTERY~2
ToolGroup=JDTools
