### ISSUE TITLE
Alteryx not loading AlteryxAddins

### ISSUE THREAD

**Issue by mjakefranklin** [jdunkerley/AlteryxAddIns#43]
I followed the instructions, and was able to run Install.bat successfully.  I have verified that the INI file has been installed here:

C:\Program Files\Alteryx\Settings\AdditionalPlugins\JDTools.ini

The file contents:

```
[Settings]
x64Path=C:\OmniBus\ALTERY~2
x86Path=C:\OmniBus\ALTERY~2
ToolGroup=JDTools
```
However, after restarting Alteryx, the new category doesn't show up, nor do any of the new tools.  Even if I change the values in the INI file above to "C:\OmniBus\AlteryxAddIns", it still won't load.

Appreciate all the work you do!

**Comment by jdunkerley** [comment]
@mjakefranklin They should be loaded but there has been a bug in Alteryx from 10.5 until 11.0 which meant it ignored the tool group. They should be in the Laboratory tool group. Let me know if they are.

**Comment by mjakefranklin** [comment]
@jdunkerley Unfortunately, there's nothing under the "Laboratory" category either.  Is there any way to troubleshoot or verify what is actually getting loaded?

**Comment by jdunkerley** [comment]
unfortunately not easily. if you want to do a google hangout or equivalent more than happy to

**Comment by jdunkerley** [comment]
@mjakefranklin only thing I can suggest is make sure the files in the folder are unblocked. Try running:
`powershell -command "gci C:\OmniBus\AlteryxAddIns | Unblock-File"`

That should unblock any files

**Comment by mjakefranklin** [comment]
Thanks @jdunkerley.  No dice on Unblock-File.  I should have more time to troubleshoot next week.  In the meantime, I may try testing the install on a separate installation.

**Comment by mjakefranklin** [comment]
Tested under Alteryx 11.0.3.25674, still no dice.

To be honest, I'm a bit new when it comes to working with custom Alteryx plugins.  Does the project need to be compiled?

**Comment by jdunkerley** [comment]
No should be enough to download the release zip, extract and run the install script :(
You would need .Net installed but that is a pre-requisite for Alteryx so should be there
If you are willing I suggest we do a google hangout or equivalent

**Comment by mjakefranklin** [comment]
@jdunkerley I could do a hangout this afternoon or any time tomorrow.

**Comment by jdunkerley** [comment]
@mjakefranklin drop me an email at james.dunkerley@gmail.com and we can set a hangout up

**Comment by jdunkerley** [comment]
Resolved
