### ISSUE TITLE
Installing into Alteryx 11.0.6

### ISSUE THREAD

**Issue by pgensler** [jdunkerley/AlteryxAddIns#46]
Would you be able to clarify how exactly to install the Omnibus tools into Alteryx? I'm trying to install them into 11.0.6, and for some reason, I must not be installing it properly with the batch file script. It seems like there are multiple Install.Bat scripts, so I just want to confirm which one I should be using.

I get this error when I'm installing v0.5.4. Any help would be appreciated. Thanks.
![image](https://user-images.githubusercontent.com/7308115/28146409-4534b8f2-673f-11e7-9197-e43e9649c45a.png)

**Comment by jdunkerley** [comment]
Installation process should be:
- Download the release zip
- Extract to a folder you want to keep it in (it will run from this location within Alteryx)
- Run the Install.bat
- Accept the UAC pop up screen

From the screenshot it looks like you are running it still compressed.

Which edition of WIndows are you using?

**Comment by pgensler** [comment]
I am using Windows 7, but I was unable to find the correct link for where to download the latest release, as when I use the link on your blog the page does not exist. I tried to clone the repo as a zip file, but I'm not sure that was the correct way of installing this.
https://github.com/jdunkerley/AlteryxAddIns/releases/tag/0.5.3
Thoughts?

**Comment by jdunkerley** [comment]
Try this link: https://github.com/jdunkerley/AlteryxAddIns/releases/download/v0.5.4/AlteryxOmniBus.v0.5.4.zip

That will download the 0.5.4 release

I'll check the links on my blog

**Comment by pgensler** [comment]
So after running the bat.script, it seems like some of the tools mentioned in the blog are not appearing in the toolbar. Should they have a new group/tab? I don't see a workflow in the link provided with a unit test to verify if the macros are installed properly.

**Comment by jdunkerley** [comment]
Unit tests are https://github.com/jdunkerley/AlteryxAddIns/releases/download/v0.5.4/AlteryxOmniBus.Tests.v0.5.4.zip

If installed correctly there should be a new OmniBus tool group on the toolbar

**Comment by pgensler** [comment]
Yeah I don't think the installation worked for me. I don't see an OnmiBus tool group on the toolbar, and I get an error stating I have an invalid file directory when I try to run the tests. I do have the Crew Macros installed however.

**Comment by jdunkerley** [comment]
Weird. I have put together a new installer not using PowerShell.

Try https://github.com/jdunkerley/AlteryxAddIns/releases/download/v0.5.4/AlteryxOmniBus.v0.5.4.1.NoPowerShell.zip

Which version of Windows are you on?

**Comment by pgensler** [comment]
I'd be free for a Google Hangout to share how I am installing the Macro, if that might be easier to understand how I am running the tests. I'm using Windows 7. I'll try installing with the provided link. What version of powershell did you develop it in? I know that there has been some major changes to the language, so maybe I have an old version, which could cause some erroneous error to be thrown?

**Comment by jdunkerley** [comment]
It's based on PowerShell 3 - which I think is a later version than on Win7.

Let me know how you get on with the batch script version if it doesn't work then lets sort out a hangout time

**Comment by pgensler** [comment]
The batch script did not seem to work. When I tried to install using the Powershell script, I know one tool had installed, but not on its own tab separate tab. I've tried using 11.3.2 to see if that made a difference, but I don't think so. Do you have any time today to do a quick Hangout?

**Comment by jdunkerley** [comment]
sure. do you want to DM on Alteryx community and we can set the call up

**Comment by pgensler** [comment]
sounds good.

**Comment by jdunkerley** [comment]
Issues:
- Unblocking in Win7
- No AdditionalPlugin folder

Will patch the current installer to create folder and look into Unblock-File in batch file.

For now after downloading the zip file, goto  properties and unblock before extracting

**Comment by jdunkerley** [comment]
I have created a new version of 0.5.4.1 without PowerShell.

It should now create the missing folder and unblock the files.

Hopefully https://github.com/jdunkerley/AlteryxAddIns/releases/download/v0.5.4/AlteryxOmniBus.v0.5.4.1.NoPowerShell.zip should just be download, extract, run Install.bat on Win7

**Comment by pgensler** [comment]
So I tried to install v1.3.0.0 of the Alteryx Formula Add-in's, and I believe I'm getting this same error, but in Windows 10 with Alteryx 11.7.
I believe last time this was related to not having the predictive tools installed, which I do not have installed.

I can try to move the scripts to where it will install, and see if that does the trick.
It might be worth noting in the readme to state that the files should start in your Macros folder, or somewhere other than your downloads folder for install.
